### ISSUE TITLE
Generating Logseq .md pages with a spreadsheet, Video Demo

### ISSUE THREAD

**Issue by candideu** [Arrowyz01/csv2logseq_block#1]
Hello! I found this plugin in the Discord chat and it looks really interesting!

I'm looking for a way to automatically generate logseq files from a spreadsheet table (can be .csv) and auto-populate certain fields from variable values in a template, kind of like mail merge. I'd like to know if your plugin could accomplish this.

For example, imagine if I had a `template.md` file that looked like this:

```
# %page-title%

Hey %name%! Welcome to the page! Here is your custom image:
![%image-URL%]
```

Then, I had a `data.csv` that looked something like this:
| page-title | name           | image-URL                                        |
|-------------|----------------|--------------------------------------------------|
|     Page1   |    Aya         |     www.website.com/image.jpg |
|     Page2   |    Obi         |      www.example.com/photo.png |
|     Page3   |    Ashanti |       www.web-site.com/illustration.gif |

Once the plugin script is run, three pages would be generated:

`Page1.md`:

```
# Page1

Hey Aya! Welcome to the page! Here is your custom image:
![www.website.com/image.jpg]
```

`Page2.md`:

```
# Page2

Hey Obi! Welcome to the page! Here is your custom image:
![www.example.com/photo.png]
```

`Page3.md`:

```
# Page3

Hey Ashanti! Welcome to the page! Here is your custom image:
![www.web-site.com/illustration.gif]
```

Does the plugin work like this?

_Edit: Earlier, I asked if a there was a video demo, but I see one now._

**Comment by Arrowyz01** [comment]
Hi! Thanks for asking! But actually, the original script cannot do the things you want... But I just wrote a new script that does exactly what you described. Feel free to try! 

I put the new script and examples in csv2md_by_template folder, you can go there by click:
https://github.com/Arrowyz01/csv2logseq_block/tree/main/csv2md_by_template

**Comment by candideu** [comment]
> Hi! Thanks for asking! But actually, the original script cannot do the things you want... But I just wrote a new script that does exactly what you described. Feel free to try!
> 
> I put the new script and examples in csv2md_by_template folder, you can go there by click: https://github.com/Arrowyz01/csv2logseq_block/tree/main/csv2md_by_template

@Arrowyz01 Wow, this incredible, thank you for taking the time to make a new script! I can't wait to try this on Windows.

I could see this new script being useful to other users outside of Logseq as well. Do you think it would be worth creating a separate repository for it as well?

**Comment by Arrowyz01** [comment]
Yeah! Great recommendation! Thanks!
And I put new repo here:
https://github.com/Arrowyz01/csv2md_by_template

**Comment by candideu** [comment]
Fantastic!
